/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

/**
 *
 * @author aanishparajuli
 */
public class LogoutPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogoutPanel
     */
    public LogoutPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutCardPanel = new javax.swing.JPanel();
        logoutIconLabel = new javax.swing.JLabel();
        logoutQuestionLabel = new javax.swing.JLabel();
        logoutSubLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        topBarPanel = new javax.swing.JPanel();
        pageTitleLabel = new javax.swing.JLabel();
        adminCircleLabel = new javax.swing.JLabel();
        adminNameLabel = new javax.swing.JLabel();

        logoutCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        logoutCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logoutIconLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 60)); // NOI18N
        logoutIconLabel.setForeground(new java.awt.Color(0, 102, 204));
        logoutIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutIconLabel.setText("⚪");

        logoutQuestionLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        logoutQuestionLabel.setForeground(new java.awt.Color(22, 54, 120));
        logoutQuestionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutQuestionLabel.setText("Are you sure you want to logout?");

        logoutSubLabel.setForeground(new java.awt.Color(100, 100, 100));
        logoutSubLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutSubLabel.setText("You will be returned to the login screen.");

        logoutButton.setBackground(new java.awt.Color(0, 102, 204));
        logoutButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorderPainted(false);
        logoutButton.setPreferredSize(new java.awt.Dimension(140, 40));
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        cancelButton.setBackground(new java.awt.Color(220, 228, 245));
        cancelButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(22, 54, 120));
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.setPreferredSize(new java.awt.Dimension(140, 40));
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        javax.swing.GroupLayout logoutCardPanelLayout = new javax.swing.GroupLayout(logoutCardPanel);
        logoutCardPanel.setLayout(logoutCardPanelLayout);
        logoutCardPanelLayout.setHorizontalGroup(
            logoutCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutIconLabel, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutQuestionLabel, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutSubLabel, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, logoutCardPanelLayout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        logoutCardPanelLayout.setVerticalGroup(
            logoutCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutCardPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(logoutIconLabel)
                .addGap(24, 24, 24)
                .addComponent(logoutQuestionLabel)
                .addGap(10, 10, 10)
                .addComponent(logoutSubLabel)
                .addGap(32, 32, 32)
                .addGroup(logoutCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        topBarPanel.setBackground(new java.awt.Color(255, 255, 255));

        pageTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        pageTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        pageTitleLabel.setText("Logout");

        adminCircleLabel.setBackground(new java.awt.Color(0, 102, 204));
        adminCircleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adminCircleLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminCircleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminCircleLabel.setText("Ad");
        adminCircleLabel.setOpaque(true);
        adminCircleLabel.setPreferredSize(new java.awt.Dimension(38, 38));

        adminNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adminNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        adminNameLabel.setText("Admin");

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pageTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 782, Short.MAX_VALUE)
                .addComponent(adminCircleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(adminNameLabel)
                .addGap(24, 24, 24))
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageTitleLabel)
                    .addComponent(adminCircleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNameLabel))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(topBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(logoutCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(logoutCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminCircleLabel;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel logoutCardPanel;
    private javax.swing.JLabel logoutIconLabel;
    private javax.swing.JLabel logoutQuestionLabel;
    private javax.swing.JLabel logoutSubLabel;
    private javax.swing.JLabel pageTitleLabel;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
