/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

/**
 *
 * @author aanishparajuli
 */
public class SchedulePanel extends javax.swing.JPanel {

    /**
     * Creates new form SchedulePanel
     */
    public SchedulePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContentPanel = new javax.swing.JPanel();
        scheduleCardPanel = new javax.swing.JPanel();
        scheduleTitleLabel = new javax.swing.JLabel();
        time1Label = new javax.swing.JLabel();
        dot1Label = new javax.swing.JLabel();
        entry1Label = new javax.swing.JLabel();
        time2Label = new javax.swing.JLabel();
        dot2Label = new javax.swing.JLabel();
        entry2Label = new javax.swing.JLabel();
        time3Label = new javax.swing.JLabel();
        dot3Label = new javax.swing.JLabel();
        entry3Label = new javax.swing.JLabel();
        time4Label = new javax.swing.JLabel();
        dot4Label = new javax.swing.JLabel();
        entry4Label = new javax.swing.JLabel();
        time5Label = new javax.swing.JLabel();
        dot5Label = new javax.swing.JLabel();
        entry5Label = new javax.swing.JLabel();
        topBarPanel1 = new javax.swing.JPanel();
        pageTitleLabel1 = new javax.swing.JLabel();
        adminCircleLabel1 = new javax.swing.JLabel();
        adminNameLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        mainContentPanel.setBackground(new java.awt.Color(255, 255, 255));

        scheduleCardPanel.setBackground(new java.awt.Color(255, 255, 255));

        scheduleTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        scheduleTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        scheduleTitleLabel.setText("Today's schedule");

        time1Label.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        time1Label.setForeground(new java.awt.Color(0, 102, 204));
        time1Label.setText("09:00 AM");
        time1Label.setPreferredSize(new java.awt.Dimension(80, 20));

        dot1Label.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        dot1Label.setForeground(new java.awt.Color(0, 102, 204));
        dot1Label.setText("●");

        entry1Label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        entry1Label.setForeground(new java.awt.Color(40, 40, 40));
        entry1Label.setText("Dr. Sharma — General checkup, Patient Anmol");

        time2Label.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        time2Label.setForeground(new java.awt.Color(0, 102, 204));
        time2Label.setText("10:30 AM");
        time2Label.setPreferredSize(new java.awt.Dimension(80, 20));

        dot2Label.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        dot2Label.setForeground(new java.awt.Color(0, 102, 204));
        dot2Label.setText("●");

        entry2Label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        entry2Label.setForeground(new java.awt.Color(40, 40, 40));
        entry2Label.setText("Dr. Paudel — Follow-up, Patient Sita");

        time3Label.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        time3Label.setForeground(new java.awt.Color(0, 102, 204));
        time3Label.setText("12:00 PM");
        time3Label.setPreferredSize(new java.awt.Dimension(80, 20));

        dot3Label.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        dot3Label.setForeground(new java.awt.Color(0, 102, 204));
        dot3Label.setText("●");

        entry3Label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        entry3Label.setForeground(new java.awt.Color(40, 40, 40));
        entry3Label.setText("Dr. Thapa — Consultation, Patient Ram");

        time4Label.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        time4Label.setForeground(new java.awt.Color(0, 102, 204));
        time4Label.setText("02:00 PM");
        time4Label.setPreferredSize(new java.awt.Dimension(80, 20));

        dot4Label.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        dot4Label.setForeground(new java.awt.Color(0, 120, 204));
        dot4Label.setText("●");

        entry4Label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        entry4Label.setForeground(new java.awt.Color(40, 40, 40));
        entry4Label.setText("Dr. Shrestha — Lab review, Patient Priya");

        time5Label.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        time5Label.setForeground(new java.awt.Color(0, 102, 204));
        time5Label.setText("04:00 PM");
        time5Label.setPreferredSize(new java.awt.Dimension(80, 20));

        dot5Label.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        dot5Label.setForeground(new java.awt.Color(140, 190, 255));
        dot5Label.setText("●");

        entry5Label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        entry5Label.setForeground(new java.awt.Color(40, 40, 40));
        entry5Label.setText("Dr. Karki — Emergency consult, Patient Bikash");

        javax.swing.GroupLayout scheduleCardPanelLayout = new javax.swing.GroupLayout(scheduleCardPanel);
        scheduleCardPanel.setLayout(scheduleCardPanelLayout);
        scheduleCardPanelLayout.setHorizontalGroup(
            scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scheduleTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                        .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                                .addComponent(time3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dot3Label))
                            .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                                    .addComponent(time5Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(dot5Label))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scheduleCardPanelLayout.createSequentialGroup()
                                    .addComponent(time4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(dot4Label))))
                        .addGap(18, 18, 18)
                        .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entry4Label)
                            .addComponent(entry5Label)
                            .addComponent(entry3Label)))
                    .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                        .addComponent(time2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dot2Label)
                        .addGap(18, 18, 18)
                        .addComponent(entry2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                        .addComponent(time1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dot1Label)
                        .addGap(18, 18, 18)
                        .addComponent(entry1Label)))
                .addContainerGap(558, Short.MAX_VALUE))
        );
        scheduleCardPanelLayout.setVerticalGroup(
            scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scheduleTitleLabel)
                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dot1Label)
                            .addComponent(entry1Label))
                        .addGap(18, 18, 18)
                        .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dot2Label))
                        .addGap(18, 18, 18)
                        .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dot3Label)
                            .addComponent(time3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scheduleCardPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(entry2Label)
                        .addGap(18, 18, 18)
                        .addComponent(entry3Label)
                        .addGap(10, 10, 10)))
                .addGap(7, 7, 7)
                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dot4Label)
                    .addComponent(entry4Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time5Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dot5Label)
                    .addComponent(entry5Label))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainContentPanelLayout = new javax.swing.GroupLayout(mainContentPanel);
        mainContentPanel.setLayout(mainContentPanelLayout);
        mainContentPanelLayout.setHorizontalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(scheduleCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        mainContentPanelLayout.setVerticalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainContentPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(scheduleCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        topBarPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pageTitleLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        pageTitleLabel1.setForeground(new java.awt.Color(0, 102, 204));
        pageTitleLabel1.setText("Schedule");

        adminCircleLabel1.setBackground(new java.awt.Color(0, 102, 204));
        adminCircleLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adminCircleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        adminCircleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminCircleLabel1.setText("Ad");
        adminCircleLabel1.setOpaque(true);
        adminCircleLabel1.setPreferredSize(new java.awt.Dimension(38, 38));

        adminNameLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adminNameLabel1.setForeground(new java.awt.Color(51, 51, 51));
        adminNameLabel1.setText("Admin");

        javax.swing.GroupLayout topBarPanel1Layout = new javax.swing.GroupLayout(topBarPanel1);
        topBarPanel1.setLayout(topBarPanel1Layout);
        topBarPanel1Layout.setHorizontalGroup(
            topBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pageTitleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 905, Short.MAX_VALUE)
                .addComponent(adminCircleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(adminNameLabel1)
                .addGap(24, 24, 24))
        );
        topBarPanel1Layout.setVerticalGroup(
            topBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(topBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageTitleLabel1)
                    .addComponent(adminCircleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNameLabel1))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topBarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topBarPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminCircleLabel1;
    private javax.swing.JLabel adminNameLabel1;
    private javax.swing.JLabel dot1Label;
    private javax.swing.JLabel dot2Label;
    private javax.swing.JLabel dot3Label;
    private javax.swing.JLabel dot4Label;
    private javax.swing.JLabel dot5Label;
    private javax.swing.JLabel entry1Label;
    private javax.swing.JLabel entry2Label;
    private javax.swing.JLabel entry3Label;
    private javax.swing.JLabel entry4Label;
    private javax.swing.JLabel entry5Label;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JLabel pageTitleLabel1;
    private javax.swing.JPanel scheduleCardPanel;
    private javax.swing.JLabel scheduleTitleLabel;
    private javax.swing.JLabel time1Label;
    private javax.swing.JLabel time2Label;
    private javax.swing.JLabel time3Label;
    private javax.swing.JLabel time4Label;
    private javax.swing.JLabel time5Label;
    private javax.swing.JPanel topBarPanel1;
    // End of variables declaration//GEN-END:variables
}
