/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Aakash Das
 */
public class AccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountPanel
     */
    public AccountPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDob = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCurrentPassword = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 700));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("⚙️ Account Settings");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 240, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("🔔");
        add(jLabel2);
        jLabel2.setBounds(690, 30, 30, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(150, 150, 150));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FULL NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 10, 210, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Abx");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 30, 210, 20);

        add(jPanel1);
        jPanel1.setBounds(30, 90, 210, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(150, 150, 150));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AGE");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 10, 200, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("28");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 30, 200, 20);

        add(jPanel2);
        jPanel2.setBounds(260, 90, 200, 60);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(150, 150, 150));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DATE OF BIRTH");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 10, 230, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("12 Jan 1997");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(0, 30, 230, 20);

        add(jPanel3);
        jPanel3.setBounds(480, 90, 230, 60);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel4.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(150, 150, 150));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("LOCATION");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(0, 10, 210, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Kathmandu");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(0, 30, 210, 20);

        add(jPanel4);
        jPanel4.setBounds(30, 170, 210, 60);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel5.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(150, 150, 150));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PHONE NO.");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(0, 10, 200, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("+977-9800000000");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(0, 30, 200, 20);

        add(jPanel5);
        jPanel5.setBounds(260, 170, 200, 60);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel6.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(150, 150, 150));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("EMAIL");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(0, 10, 230, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("1@email.com");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(0, 30, 230, 20);

        add(jPanel6);
        jPanel6.setBounds(480, 170, 230, 60);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("✏️ Edit Profile Information");
        add(jLabel15);
        jLabel15.setBounds(30, 270, 250, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(150, 150, 150));
        jLabel16.setText("CHANGE DATE OF BIRTH");
        add(jLabel16);
        jLabel16.setBounds(30, 310, 150, 20);

        txtDob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDob.setForeground(new java.awt.Color(150, 150, 150));
        // txtDob.setText(...) removed for JDateChooser
        add(txtDob);
        txtDob.setBounds(30, 335, 230, 35);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(150, 150, 150));
        jLabel17.setText("CHANGE PHONE NO.");
        add(jLabel17);
        jLabel17.setBounds(420, 310, 150, 20);

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(150, 150, 150));
        txtPhone.setText("Enter new phone number");
        add(txtPhone);
        txtPhone.setBounds(420, 335, 290, 35);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(150, 150, 150));
        jLabel18.setText("CHANGE EMAIL");
        add(jLabel18);
        jLabel18.setBounds(30, 390, 150, 20);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(150, 150, 150));
        txtEmail.setText("Enter new email address");
        add(txtEmail);
        txtEmail.setBounds(30, 415, 230, 35);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(150, 150, 150));
        jLabel19.setText("CHANGE PASSWORD");
        add(jLabel19);
        jLabel19.setBounds(420, 390, 150, 20);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(150, 150, 150));
        txtPassword.setText("Enter new password");
        add(txtPassword);
        txtPassword.setBounds(420, 415, 290, 35);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(150, 150, 150));
        jLabel20.setText("CURRENT PASSWORD (REQUIRED TO CONFIRM)");
        add(jLabel20);
        jLabel20.setBounds(30, 480, 280, 20);

        txtCurrentPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCurrentPassword.setForeground(new java.awt.Color(150, 150, 150));
        txtCurrentPassword.setText("Enter current password");
        add(txtCurrentPassword);
        txtCurrentPassword.setBounds(30, 505, 230, 35);

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(30, 100, 180));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 100, 180)));
        add(btnCancel);
        btnCancel.setBounds(30, 580, 110, 35);

        btnConfirm.setBackground(new java.awt.Color(30, 100, 180));
        btnConfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirm");
        add(btnConfirm);
        btnConfirm.setBounds(160, 580, 110, 35);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtCurrentPassword;
    private com.toedter.calendar.JDateChooser txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    public void displayPatientProfile(model.Patient p, String username) {
        jLabel4.setText(p.getFullName());
        jLabel6.setText(String.valueOf(p.getAge()));
        if (p.getDob() != null) {
            jLabel8.setText(p.getDob().toString());
        }
        jLabel10.setText(p.getAddress());
        jLabel12.setText(p.getContactNumber());
        jLabel14.setText(username);
    }

    public com.toedter.calendar.JDateChooser getTxtDob() {
        return txtDob;
    }

    public javax.swing.JTextField getTxtPhone() {
        return txtPhone;
    }

    public javax.swing.JTextField getTxtEmail() {
        return txtEmail;
    }

    public javax.swing.JTextField getTxtPassword() {
        return txtPassword;
    }

    public javax.swing.JTextField getTxtCurrentPassword() {
        return txtCurrentPassword;
    }

    public javax.swing.JButton getBtnConfirm() {
        return btnConfirm;
    }
}
