package view;
import java.awt.CardLayout;
import controller.AdminController;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author aanishparajuli
 */
public class admin extends javax.swing.JFrame {
    CardLayout cardLayout;
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(admin.class.getName());

    /**
     * Creates new form admin
     */
 public admin() {
    initComponents();
    setSize(1200, 800);
    setLocationRelativeTo(null);
    
    cardLayout = new CardLayout();
    contentPanel.setLayout(cardLayout);
    new AdminController(this);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(22, 54, 120));
        sidebar.setPreferredSize(new java.awt.Dimension(250, 800));
        sidebar.setLayout(new javax.swing.BoxLayout(sidebar, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  🏥 HQMS");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 80));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 80));
        sidebar.add(jLabel1);

        jButton2.setText("🏠  Home");
        jButton2.setBackground(new java.awt.Color(22, 54, 120));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setFocusPainted(false);
        jButton2.setBorderPainted(false);
        jButton2.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(250, 50));
        sidebar.add(jButton2);

        jButton3.setText("🗓️  Schedule");
        jButton3.setBackground(new java.awt.Color(22, 54, 120));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setFocusPainted(false);
        jButton3.setBorderPainted(false);
        jButton3.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(250, 50));
        sidebar.add(jButton3);

        jButton4.setText("🧾  Report");
        jButton4.setBackground(new java.awt.Color(22, 54, 120));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setFocusPainted(false);
        jButton4.setBorderPainted(false);
        jButton4.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton4.setPreferredSize(new java.awt.Dimension(250, 50));
        sidebar.add(jButton4);

        jButton5.setBackground(new java.awt.Color(22, 54, 120));
        jButton5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("🔔  Notification");
        jButton5.setBorderPainted(false);
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(250, 50));
        sidebar.add(jButton5);

        jButton6.setText("🙍🏻‍  Create user");
        jButton6.setBackground(new java.awt.Color(22, 54, 120));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setFocusPainted(false);
        jButton6.setBorderPainted(false);
        jButton6.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton6.setPreferredSize(new java.awt.Dimension(250, 50));
        sidebar.add(jButton6);

        jButton8.setText("🙍🏻‍  Manage User");
        jButton8.setBackground(new java.awt.Color(22, 54, 120));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.setFocusPainted(false);
        jButton8.setBorderPainted(false);
        jButton8.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton8.setPreferredSize(new java.awt.Dimension(250, 50));
        sidebar.add(jButton8);

        jButton9.setText("🩺  Manage doctor");
        jButton9.setBackground(new java.awt.Color(22, 54, 120));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.setFocusPainted(false);
        jButton9.setBorderPainted(false);
        jButton9.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton9.setPreferredSize(new java.awt.Dimension(250, 50));
        sidebar.add(jButton9);

        jButton7.setText("⇤  Logout");
        jButton7.setBackground(new java.awt.Color(22, 54, 120));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setFocusPainted(false);
        jButton7.setBorderPainted(false);
        jButton7.setMaximumSize(new java.awt.Dimension(250, 50));
        jButton7.setPreferredSize(new java.awt.Dimension(250, 50));
        sidebar.add(jButton7);

        getContentPane().add(sidebar, java.awt.BorderLayout.WEST);

        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setActiveButton(javax.swing.JButton activeBtn) {
        javax.swing.JButton[] buttons = {jButton2, jButton3, jButton4, jButton5, jButton6, jButton8, jButton9, jButton7};
        java.awt.Color normalBg = new java.awt.Color(22, 54, 120);
        java.awt.Color activeBg = new java.awt.Color(51, 102, 255);
        for (javax.swing.JButton btn : buttons) {
            btn.setBackground(btn == activeBtn ? activeBg : normalBg);
            btn.setOpaque(true);
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables



public javax.swing.JButton getBtnHome()       { return jButton2; }
public javax.swing.JButton getBtnSchedule()   { return jButton3; }
public javax.swing.JButton getBtnReport()     { return jButton4; }
public javax.swing.JButton getBtnNotification() { return jButton5; }
public javax.swing.JButton getBtnCreateUser() { return jButton6; }
public javax.swing.JButton getBtnLogout()     { return jButton7; }
public javax.swing.JButton getBtnManageUser() { return jButton8; }
public javax.swing.JButton getBtnManageDoctor() { return jButton9; }

public javax.swing.JPanel getContentPanel() { return contentPanel; }
public java.awt.CardLayout getCardLayout() { return cardLayout; }

}