package view;
import java.awt.CardLayout;
import controller.AdminController;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author aanishparajuli
 */
public class admin extends javax.swing.JFrame {
    CardLayout cardLayout;
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(admin.class.getName());

    /**
     * Creates new form admin
     */
 public admin() {
    initComponents();
    setSize(1200, 800);
    setLocationRelativeTo(null);
    
    cardLayout = new CardLayout();
    contentPanel.setLayout(cardLayout);
    new AdminController(this);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        // Deep blue professional sidebar
        sidebar.setBackground(new java.awt.Color(22, 54, 120));
        sidebar.setPreferredSize(new java.awt.Dimension(250, 800));
        sidebar.setLayout(new javax.swing.BoxLayout(sidebar, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  🏥 HQMS");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 80));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 80));
        sidebar.add(jLabel1);

        java.awt.Color btnBg = new java.awt.Color(22, 54, 120);
        java.awt.Color btnFg = new java.awt.Color(255, 255, 255);
        java.awt.Font btnFont = new java.awt.Font("Helvetica Neue", 0, 16);
        java.awt.Dimension btnSize = new java.awt.Dimension(250, 50);

        javax.swing.JButton[] buttons = {jButton2, jButton10, jButton3, jButton4, jButton5, jButton6, jButton8, jButton9, jButton7};
        String[] labels = {"🏠  Home", "🖥️  Dashboard", "🗓️  Schedule", "🧾  Report", "🔔  Notification", "🙍🏻‍  Create user", "🙍🏻‍  Manage User", "🩺  Manage doctor", "⇤  Logout"};
        java.awt.event.ActionListener[] actions = {
            this::jButton2ActionPerformed, this::jButton10ActionPerformed, this::jButton3ActionPerformed, 
            this::jButton4ActionPerformed, this::jButton5ActionPerformed, this::jButton6ActionPerformed, 
            this::jButton8ActionPerformed, this::jButton9ActionPerformed, this::jButton7ActionPerformed
        };

        for (int i = 0; i < buttons.length; i++) {
            javax.swing.JButton btn = buttons[i];
            btn.setText(labels[i]);
            btn.setFont(btnFont);
            btn.setBackground(btnBg);
            btn.setForeground(btnFg);
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            btn.setMaximumSize(btnSize);
            btn.setPreferredSize(btnSize);
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btn.addActionListener(actions[i]);
            
            // Add margin for text
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
            
            if (i == buttons.length - 1) {
                sidebar.add(javax.swing.Box.createVerticalGlue()); // Push logout to bottom
            }
            sidebar.add(btn);
        }

        getContentPane().add(sidebar, java.awt.BorderLayout.WEST);

        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables



public javax.swing.JButton getBtnHome()       { return jButton2; }
public javax.swing.JButton getBtnDashboard()  { return jButton10; }
public javax.swing.JButton getBtnSchedule()   { return jButton3; }
public javax.swing.JButton getBtnReport()     { return jButton4; }
public javax.swing.JButton getBtnNotification() { return jButton5; }
public javax.swing.JButton getBtnCreateUser() { return jButton6; }
public javax.swing.JButton getBtnLogout()     { return jButton7; }
public javax.swing.JButton getBtnManageUser() { return jButton8; }
public javax.swing.JButton getBtnManageDoctor() { return jButton9; }

public javax.swing.JPanel getContentPanel() { return contentPanel; }
public java.awt.CardLayout getCardLayout() { return cardLayout; }

}