/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Aakash Das
 */
public class AppointmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form AppointmentPanel
     */
    public AppointmentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbDoctor = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 700));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("📅 Book New Appointment");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 320, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        jLabel2.setText("🔔");
        add(jLabel2);
        jLabel2.setBounds(690, 30, 30, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(80, 80, 80));
        jLabel3.setText("Select Department");
        add(jLabel3);
        jLabel3.setBounds(40, 80, 150, 20);

        cmbDepartment.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cardiology", "Neurology", "Orthopedics", "Pediatrics", "Dermatology", "General Medicine" }));
        add(cmbDepartment);
        cmbDepartment.setBounds(40, 105, 660, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(80, 80, 80));
        jLabel4.setText("Select Doctor");
        add(jLabel4);
        jLabel4.setBounds(40, 155, 120, 20);

        cmbDoctor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cmbDoctor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dr. John Smith", "Dr. Sarah Johnson", "Dr. Ramesh Sharma", "Dr. Emily Davis" }));
        add(cmbDoctor);
        cmbDoctor.setBounds(40, 180, 320, 35);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 80));
        jLabel5.setText("Select Date");
        add(jLabel5);
        jLabel5.setBounds(390, 155, 100, 20);

        cmbDate.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        // cmbDate.setModel(...) removed for JDateChooser
        add(cmbDate);
        cmbDate.setBounds(390, 180, 310, 35);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(80, 80, 80));
        jLabel6.setText("Select Time");
        add(jLabel6);
        jLabel6.setBounds(40, 230, 100, 20);

        txtTime.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtTime.setText("10:30 AM");
        add(txtTime);
        txtTime.setBounds(40, 255, 320, 35);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(80, 80, 80));
        jLabel7.setText("Reason (Optional)");
        add(jLabel7);
        jLabel7.setBounds(390, 230, 150, 20);

        txtReason.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtReason.setForeground(new java.awt.Color(180, 180, 180));
        txtReason.setText("Optional");
        add(txtReason);
        txtReason.setBounds(390, 255, 310, 35);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(80, 80, 80));
        jLabel8.setText("Regular checkup and consultation");
        add(jLabel8);
        jLabel8.setBounds(40, 310, 300, 20);

        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(txtDescription);
        txtDescription.setBounds(40, 340, 660, 35);

        btnConfirm.setBackground(new java.awt.Color(30, 100, 180));
        btnConfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirm Appointment");
        add(btnConfirm);
        btnConfirm.setBounds(250, 400, 220, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(180, 180, 180));
        jLabel9.setText("Book New Appointment");
        add(jLabel9);
        jLabel9.setBounds(5, 5, 150, 14);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private com.toedter.calendar.JDateChooser cmbDate;
    private javax.swing.JComboBox cmbDepartment;
    private javax.swing.JComboBox cmbDoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtReason;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox getCmbDepartment() {
        return cmbDepartment;
    }

    public javax.swing.JComboBox getCmbDoctor() {
        return cmbDoctor;
    }

    public com.toedter.calendar.JDateChooser getCmbDate() {
        return cmbDate;
    }

    public javax.swing.JTextField getTxtTime() {
        return txtTime;
    }

    public javax.swing.JTextField getTxtReason() {
        return txtReason;
    }

    public javax.swing.JTextField getTxtDescription() {
        return txtDescription;
    }

    public javax.swing.JButton getBtnConfirm() {
        return btnConfirm;
    }
}
