/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import com.toedter.calendar.JDateChooser;
/**
 *
 * @author aanishparajuli
 */
public class CreateuserPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateuserPanel
     */
    public CreateuserPanel() {
        initComponents();
        fixLayout();
    }

    private void fixLayout() {
        this.setLayout(new java.awt.BorderLayout());
        this.removeAll();
        this.add(topBarPanel, java.awt.BorderLayout.NORTH);
        
        javax.swing.JPanel centerWrapper = new javax.swing.JPanel(new java.awt.GridBagLayout());
        centerWrapper.setBackground(new java.awt.Color(235, 240, 251)); // Same as dashboard
        
        // Ensure formCardPanel doesn't demand huge width that breaks GridBagLayout centering
        formCardPanel.setPreferredSize(new java.awt.Dimension(700, 750));
        formCardPanel.setMinimumSize(new java.awt.Dimension(600, 700));
        centerWrapper.add(formCardPanel);
        
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(centerWrapper);
        scrollPane.setBorder(null);
        this.add(scrollPane, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formCardPanel = new javax.swing.JPanel();
        formTitleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        roleLabel = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        phone = new javax.swing.JLabel();
        nameField1 = new javax.swing.JTextField();
        roleLabel1 = new javax.swing.JLabel();
        GenderCombobox = new javax.swing.JComboBox<>();
        Dateofbirth = new com.toedter.calendar.JDateChooser();
        DOB = new javax.swing.JLabel();
        shiftlabel = new javax.swing.JLabel();
        shiftcombobox = new javax.swing.JComboBox<>();
        topBarPanel = new javax.swing.JPanel();
        pageTitleLabel = new javax.swing.JLabel();
        adminCircleLabel = new javax.swing.JLabel();
        adminNameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        formCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        formCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        formTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        formTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        formTitleLabel.setText("New User Details");

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(100, 100, 100));
        nameLabel.setText("Full Name");

        nameField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        roleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(100, 100, 100));
        roleLabel.setText("System Role");

        roleComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receptionist", "Admin", "Doctor", " " }));
        roleComboBox.addActionListener(this::roleComboBoxActionPerformed);

        passwordLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(100, 100, 100));
        passwordLabel.setText("Password");

        passwordField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        saveButton.setBackground(new java.awt.Color(0, 102, 204));
        saveButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Create User");
        saveButton.setBorderPainted(false);
        saveButton.setPreferredSize(new java.awt.Dimension(140, 40));

        clearButton.setBackground(new java.awt.Color(220, 228, 245));
        clearButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        clearButton.setForeground(new java.awt.Color(0, 102, 204));
        clearButton.setText("Clear Form");
        clearButton.setBorderPainted(false);
        clearButton.setPreferredSize(new java.awt.Dimension(140, 40));

        phone.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(100, 100, 100));
        phone.setText("Phone");

        nameField1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        roleLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        roleLabel1.setForeground(new java.awt.Color(100, 100, 100));
        roleLabel1.setText("Gender");

        GenderCombobox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        GenderCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others", " " }));
        GenderCombobox.addActionListener(this::GenderComboboxActionPerformed);

        DOB.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        DOB.setForeground(new java.awt.Color(100, 100, 100));
        DOB.setText("Date of Birth");

        shiftlabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        shiftlabel.setForeground(new java.awt.Color(100, 100, 100));
        shiftlabel.setText("Shift");

        shiftcombobox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        shiftcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Afternoon", "Night", " " }));
        shiftcombobox.addActionListener(this::shiftcomboboxActionPerformed);

        javax.swing.GroupLayout formCardPanelLayout = new javax.swing.GroupLayout(formCardPanel);
        formCardPanel.setLayout(formCardPanelLayout);
        formCardPanelLayout.setHorizontalGroup(
            formCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCardPanelLayout.createSequentialGroup()
                .addGroup(formCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formCardPanelLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(formTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formCardPanelLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(formCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shiftcombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel)
                            .addGroup(formCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(roleComboBox, 0, 378, Short.MAX_VALUE)
                                .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameField)
                                .addGroup(formCardPanelLayout.createSequentialGroup()
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(GenderCombobox, 0, 378, Short.MAX_VALUE))
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addComponent(Dateofbirth, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shiftlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(474, Short.MAX_VALUE))
        );
        formCardPanelLayout.setVerticalGroup(
            formCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCardPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(formTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(roleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GenderCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(shiftlabel)
                .addGap(23, 23, 23)
                .addComponent(shiftcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DOB)
                .addGap(18, 18, 18)
                .addComponent(Dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(formCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        topBarPanel.setBackground(new java.awt.Color(255, 255, 255));

        pageTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        pageTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        pageTitleLabel.setText("Create User");

        adminCircleLabel.setBackground(new java.awt.Color(0, 102, 204));
        adminCircleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adminCircleLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminCircleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminCircleLabel.setText("Ad");
        adminCircleLabel.setOpaque(true);
        adminCircleLabel.setPreferredSize(new java.awt.Dimension(38, 38));

        adminNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adminNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        adminNameLabel.setText("Admin");

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pageTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 902, Short.MAX_VALUE)
                .addComponent(adminCircleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(adminNameLabel)
                .addGap(24, 24, 24))
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageTitleLabel)
                    .addComponent(adminCircleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNameLabel))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(formCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboBoxActionPerformed

    private void GenderComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderComboboxActionPerformed

    private void shiftcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shiftcomboboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB;
    private com.toedter.calendar.JDateChooser Dateofbirth;
    private javax.swing.JComboBox<String> GenderCombobox;
    private javax.swing.JLabel adminCircleLabel;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel formCardPanel;
    private javax.swing.JLabel formTitleLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nameField1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel pageTitleLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel phone;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel roleLabel1;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> shiftcombobox;
    private javax.swing.JLabel shiftlabel;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables

public javax.swing.JTextField getNameField()              { return nameField; }
public javax.swing.JTextField getNameField1()             { return nameField1; }
public com.toedter.calendar.JDateChooser getDobField()    { return Dateofbirth; }
public javax.swing.JPasswordField getPasswordField()      { return passwordField; }
public javax.swing.JComboBox<String> getGenderCombobox()  { return GenderCombobox; }
public javax.swing.JComboBox<String> getRoleComboBox()    { return roleComboBox; }
public javax.swing.JButton getSaveButton()                { return saveButton; }
public javax.swing.JButton getClearButton()               { return clearButton; }

public javax.swing.JComboBox<String> getShiftComboBox()   { return shiftcombobox; }
public javax.swing.JLabel getShiftLabel()                 { return shiftlabel; }

public void setShiftVisible(boolean visible) {
    shiftlabel.setVisible(visible);
    shiftcombobox.setVisible(visible);
}

}

