/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import dao.DashboardDAO;

/**
 *
 * @author aanishparajuli
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
 public DashboardPanel() {
    initComponents();
    fixLayout();
    loadData();
}

private void fixLayout() {
    tableCardPanel.setLayout(new java.awt.BorderLayout());
    tableCardPanel.removeAll();
    
    javax.swing.JPanel topBar = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
    topBar.setBackground(java.awt.Color.WHITE);
    topBar.add(lblSearch);
    topBar.add(txtSearch);
    topBar.add(btnSearch);
    
    javax.swing.JPanel titlePanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
    titlePanel.setBackground(java.awt.Color.WHITE);
    titlePanel.add(userMgmtLabel);
    
    javax.swing.JPanel headerPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
    headerPanel.add(titlePanel, java.awt.BorderLayout.NORTH);
    headerPanel.add(topBar, java.awt.BorderLayout.CENTER);
    
    tableCardPanel.add(headerPanel, java.awt.BorderLayout.NORTH);
    tableCardPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);
}
        
        
    
private void loadData() {
    DashboardDAO dao = new DashboardDAO();

    card1NumberLabel.setText(String.valueOf(dao.getPatientCount()));
    card2NumberLabel.setText(String.valueOf(dao.getDoctorCount()));
    card3NumberLabel.setText(String.valueOf(dao.getAppointmentCount()));
    card4NumberLabel.setText(String.valueOf(dao.getReceptionistCount()));

    // Fix date - always shows today's actual date
    String today = new java.text.SimpleDateFormat("EEEE, MMMM dd yyyy")
                       .format(new java.util.Date());
    welcomeDateLabel.setText(today);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        mainContentPanel = new javax.swing.JPanel();
        welcomeCardPanel = new javax.swing.JPanel();
        welcomeTitleLabel = new javax.swing.JLabel();
        welcomeDateLabel = new javax.swing.JLabel();
        weatherLabel = new javax.swing.JLabel();
        cardsRowPanel = new javax.swing.JPanel();
        card1Panel = new javax.swing.JPanel();
        card1NumberLabel = new javax.swing.JLabel();
        card1TextLabel = new javax.swing.JLabel();
        card2Panel = new javax.swing.JPanel();
        card2NumberLabel = new javax.swing.JLabel();
        card2TextLabel = new javax.swing.JLabel();
        card3Panel = new javax.swing.JPanel();
        card3NumberLabel = new javax.swing.JLabel();
        card3TextLabel = new javax.swing.JLabel();
        card4Panel = new javax.swing.JPanel();
        card4NumberLabel = new javax.swing.JLabel();
        card4TextLabel = new javax.swing.JLabel();
        tableCardPanel = new javax.swing.JPanel();
        userMgmtLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setBackground(new java.awt.Color(255, 255, 255));

        mainContentPanel.setBackground(new java.awt.Color(235, 240, 251));

        welcomeCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        welcomeCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        welcomeTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        welcomeTitleLabel.setForeground(new java.awt.Color(22, 54, 120));
        welcomeTitleLabel.setText("Welcome Again");

        welcomeDateLabel.setForeground(new java.awt.Color(0, 102, 204));
        welcomeDateLabel.setText("Monday, May 25 2026");

        weatherLabel.setForeground(new java.awt.Color(60, 60, 60));
        weatherLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        weatherLabel.setText("30°C  Kathmandu");

        javax.swing.GroupLayout welcomeCardPanelLayout = new javax.swing.GroupLayout(welcomeCardPanel);
        welcomeCardPanel.setLayout(welcomeCardPanelLayout);
        welcomeCardPanelLayout.setHorizontalGroup(
            welcomeCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeCardPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(welcomeCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeTitleLabel)
                    .addComponent(welcomeDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(weatherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        welcomeCardPanelLayout.setVerticalGroup(
            welcomeCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeCardPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(welcomeCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomeCardPanelLayout.createSequentialGroup()
                        .addComponent(welcomeTitleLabel)
                        .addGap(6, 6, 6)
                        .addComponent(welcomeDateLabel))
                    .addComponent(weatherLabel))
                .addGap(20, 20, 20))
        );

        cardsRowPanel.setBackground(new java.awt.Color(235, 240, 251));

        card1Panel.setBackground(new java.awt.Color(30, 90, 200));

        card1NumberLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        card1NumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        card1NumberLabel.setText("2");

        card1TextLabel.setForeground(new java.awt.Color(210, 228, 255));
        card1TextLabel.setText("Total Patients");

        javax.swing.GroupLayout card1PanelLayout = new javax.swing.GroupLayout(card1Panel);
        card1Panel.setLayout(card1PanelLayout);
        card1PanelLayout.setHorizontalGroup(
            card1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(card1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card1NumberLabel)
                    .addComponent(card1TextLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card1PanelLayout.setVerticalGroup(
            card1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(card1NumberLabel)
                .addGap(8, 8, 8)
                .addComponent(card1TextLabel)
                .addGap(22, 22, 22))
        );

        card2Panel.setBackground(new java.awt.Color(30, 120, 220));

        card2NumberLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        card2NumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        card2NumberLabel.setText("9");

        card2TextLabel.setForeground(new java.awt.Color(210, 228, 255));
        card2TextLabel.setText("Total Doctors");

        javax.swing.GroupLayout card2PanelLayout = new javax.swing.GroupLayout(card2Panel);
        card2Panel.setLayout(card2PanelLayout);
        card2PanelLayout.setHorizontalGroup(
            card2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card2PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(card2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card2NumberLabel)
                    .addComponent(card2TextLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card2PanelLayout.setVerticalGroup(
            card2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card2PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(card2NumberLabel)
                .addGap(8, 8, 8)
                .addComponent(card2TextLabel)
                .addGap(22, 22, 22))
        );

        card3Panel.setBackground(new java.awt.Color(51, 153, 255));

        card3NumberLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        card3NumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        card3NumberLabel.setText("5");

        card3TextLabel.setForeground(new java.awt.Color(210, 228, 255));
        card3TextLabel.setText("Schedules");

        javax.swing.GroupLayout card3PanelLayout = new javax.swing.GroupLayout(card3Panel);
        card3Panel.setLayout(card3PanelLayout);
        card3PanelLayout.setHorizontalGroup(
            card3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card3PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(card3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card3NumberLabel)
                    .addComponent(card3TextLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card3PanelLayout.setVerticalGroup(
            card3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card3PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(card3NumberLabel)
                .addGap(8, 8, 8)
                .addComponent(card3TextLabel)
                .addGap(22, 22, 22))
        );

        card4Panel.setBackground(new java.awt.Color(100, 180, 255));

        card4NumberLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        card4NumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        card4NumberLabel.setText("1");

        card4TextLabel.setForeground(new java.awt.Color(210, 228, 255));
        card4TextLabel.setText("Receptionist");

        javax.swing.GroupLayout card4PanelLayout = new javax.swing.GroupLayout(card4Panel);
        card4Panel.setLayout(card4PanelLayout);
        card4PanelLayout.setHorizontalGroup(
            card4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card4PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(card4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card4NumberLabel)
                    .addComponent(card4TextLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card4PanelLayout.setVerticalGroup(
            card4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card4PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(card4NumberLabel)
                .addGap(8, 8, 8)
                .addComponent(card4TextLabel)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout cardsRowPanelLayout = new javax.swing.GroupLayout(cardsRowPanel);
        cardsRowPanel.setLayout(cardsRowPanelLayout);
        cardsRowPanelLayout.setHorizontalGroup(
            cardsRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardsRowPanelLayout.createSequentialGroup()
                .addComponent(card1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(card2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(card3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(card4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardsRowPanelLayout.setVerticalGroup(
            cardsRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(card2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(card3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(card4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tableCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        tableCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        userMgmtLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        userMgmtLabel.setForeground(new java.awt.Color(0, 102, 204));
        userMgmtLabel.setText("User management");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", "", ""},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "User", "Enrolled", "Status", "Gender", "Age", "Fees"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        lblSearch.setText("Search User:");

        btnSearch.setBackground(new java.awt.Color(13, 110, 253));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");

        javax.swing.GroupLayout tableCardPanelLayout = new javax.swing.GroupLayout(tableCardPanel);
        tableCardPanel.setLayout(tableCardPanelLayout);
        tableCardPanelLayout.setHorizontalGroup(
            tableCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCardPanelLayout.createSequentialGroup()
                .addGroup(tableCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableCardPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tableCardPanelLayout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(userMgmtLabel))
                    .addGroup(tableCardPanelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        tableCardPanelLayout.setVerticalGroup(
            tableCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userMgmtLabel)
                .addGap(74, 74, 74)
                .addGroup(tableCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainContentPanelLayout = new javax.swing.GroupLayout(mainContentPanel);
        mainContentPanel.setLayout(mainContentPanelLayout);
        mainContentPanelLayout.setHorizontalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardsRowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        mainContentPanelLayout.setVerticalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(welcomeCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(cardsRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(tableCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel card1NumberLabel;
    private javax.swing.JPanel card1Panel;
    private javax.swing.JLabel card1TextLabel;
    private javax.swing.JLabel card2NumberLabel;
    private javax.swing.JPanel card2Panel;
    private javax.swing.JLabel card2TextLabel;
    private javax.swing.JLabel card3NumberLabel;
    private javax.swing.JPanel card3Panel;
    private javax.swing.JLabel card3TextLabel;
    private javax.swing.JLabel card4NumberLabel;
    private javax.swing.JPanel card4Panel;
    private javax.swing.JLabel card4TextLabel;
    private javax.swing.JPanel cardsRowPanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel tableCardPanel;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel userMgmtLabel;
    private javax.swing.JLabel weatherLabel;
    private javax.swing.JPanel welcomeCardPanel;
    private javax.swing.JLabel welcomeDateLabel;
    private javax.swing.JLabel welcomeTitleLabel;
    // End of variables declaration//GEN-END:variables

public javax.swing.JTable getDashboardTable() {
    return jTable1;
}

public javax.swing.JLabel getCard1NumberLabel() {
    return card1NumberLabel;
}

public javax.swing.JLabel getCard2NumberLabel() {
    return card2NumberLabel;
}

public javax.swing.JLabel getCard3NumberLabel() {
    return card3NumberLabel;
}

public javax.swing.JLabel getCard4NumberLabel() {
    return card4NumberLabel;
}

public javax.swing.JTextField getSearchField()  { return txtSearch; }
public javax.swing.JButton getSearchButton()    { return btnSearch; }
public javax.swing.JLabel getWelcomeDateLabel() { return welcomeDateLabel; }

}