/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author aanishparajuli
 */
public class managedoctoranddepartment extends javax.swing.JPanel {

    /**
     * Creates new form managedoctoranddepartment
     */
    public managedoctoranddepartment() {
        initComponents();
        fixLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        pnlDoctors = new javax.swing.JPanel();
        lblSearchDoc = new javax.swing.JLabel();
        txtSearchDoc = new javax.swing.JTextField();
        btnSearchDoc = new javax.swing.JButton();
        jspDoctors = new javax.swing.JScrollPane();
        tblDoctors = new javax.swing.JTable();
        pnlDoctorDetails = new javax.swing.JPanel();
        lblDocFullName = new javax.swing.JLabel();
        txtDocFullName = new javax.swing.JTextField();
        lblDocPhone = new javax.swing.JLabel();
        txtDocPhone = new javax.swing.JTextField();
        lblDocSpecialty = new javax.swing.JLabel();
        txtDocSpecialty = new javax.swing.JTextField();
        lblDocDepartment = new javax.swing.JLabel();
        txtDocDepartment = new javax.swing.JTextField();
        lblDocAvailability = new javax.swing.JLabel();
        cmbDocAvailability = new javax.swing.JComboBox<>();
        lblDocStatus = new javax.swing.JLabel();
        cmbDocStatus = new javax.swing.JComboBox<>();
        btnAddDoc = new javax.swing.JButton();
        btnUpdateDoc = new javax.swing.JButton();
        btnRemoveDoc = new javax.swing.JButton();
        btnRefreshDoc = new javax.swing.JButton();
        pnlDepartments = new javax.swing.JPanel();
        lblSearchDept = new javax.swing.JLabel();
        txtSearchDept = new javax.swing.JTextField();
        btnSearchDept = new javax.swing.JButton();
        jspDepartments = new javax.swing.JScrollPane();
        tblDepartments = new javax.swing.JTable();
        pnlDeptDetails = new javax.swing.JPanel();
        lblDeptName = new javax.swing.JLabel();
        txtDeptName = new javax.swing.JTextField();
        lblDeptHeadDoctor = new javax.swing.JLabel();
        txtDeptHeadDoctor = new javax.swing.JTextField();
        lblDeptStatus = new javax.swing.JLabel();
        cmbDeptStatus = new javax.swing.JComboBox<>();
        btnAddDept = new javax.swing.JButton();
        btnUpdateDept = new javax.swing.JButton();
        btnRemoveDept = new javax.swing.JButton();
        btnRefreshDept = new javax.swing.JButton();
        topBarPanel = new javax.swing.JPanel();
        pageTitleLabel = new javax.swing.JLabel();
        adminCircleLabel = new javax.swing.JLabel();
        adminNameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tabbedPane.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        pnlDoctors.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoctors.setLayout(null);

        lblSearchDoc.setText("Search Doctor:");
        pnlDoctors.add(lblSearchDoc);
        lblSearchDoc.setBounds(210, 40, 100, 30);
        pnlDoctors.add(txtSearchDoc);
        txtSearchDoc.setBounds(310, 40, 300, 30);

        btnSearchDoc.setBackground(new java.awt.Color(13, 110, 253));
        btnSearchDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchDoc.setText("Search");
        pnlDoctors.add(btnSearchDoc);
        btnSearchDoc.setBounds(650, 40, 100, 30);

        tblDoctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Full Name", "Phone", "Specialty", "Department", "Availability", "Status"
            }
        ));
        jspDoctors.setViewportView(tblDoctors);

        pnlDoctors.add(jspDoctors);
        jspDoctors.setBounds(80, 90, 800, 250);

        pnlDoctorDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoctorDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Doctor Details"));
        pnlDoctorDetails.setLayout(null);

        lblDocFullName.setText("Full Name");
        pnlDoctorDetails.add(lblDocFullName);
        lblDocFullName.setBounds(20, 30, 80, 20);
        pnlDoctorDetails.add(txtDocFullName);
        txtDocFullName.setBounds(100, 30, 200, 26);

        lblDocPhone.setText("Phone");
        pnlDoctorDetails.add(lblDocPhone);
        lblDocPhone.setBounds(450, 30, 80, 20);
        pnlDoctorDetails.add(txtDocPhone);
        txtDocPhone.setBounds(550, 30, 200, 26);

        lblDocSpecialty.setText("Specialty");
        pnlDoctorDetails.add(lblDocSpecialty);
        lblDocSpecialty.setBounds(20, 70, 80, 20);
        pnlDoctorDetails.add(txtDocSpecialty);
        txtDocSpecialty.setBounds(100, 70, 200, 26);

        lblDocDepartment.setText("Department");
        pnlDoctorDetails.add(lblDocDepartment);
        lblDocDepartment.setBounds(450, 70, 80, 20);
        pnlDoctorDetails.add(txtDocDepartment);
        txtDocDepartment.setBounds(550, 70, 200, 26);

        lblDocAvailability.setText("Availability");
        pnlDoctorDetails.add(lblDocAvailability);
        lblDocAvailability.setBounds(20, 110, 80, 20);

        cmbDocAvailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Non-available" }));
        pnlDoctorDetails.add(cmbDocAvailability);
        cmbDocAvailability.setBounds(100, 110, 200, 26);

        lblDocStatus.setText("Status");
        pnlDoctorDetails.add(lblDocStatus);
        lblDocStatus.setBounds(450, 110, 80, 20);

        cmbDocStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Deactive" }));
        pnlDoctorDetails.add(cmbDocStatus);
        cmbDocStatus.setBounds(550, 110, 200, 26);

        pnlDoctors.add(pnlDoctorDetails);
        pnlDoctorDetails.setBounds(80, 350, 800, 160);

        btnAddDoc.setBackground(new java.awt.Color(13, 110, 253));
        btnAddDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDoc.setText("Add Doctor");
        pnlDoctors.add(btnAddDoc);
        btnAddDoc.setBounds(130, 530, 110, 30);

        btnUpdateDoc.setBackground(new java.awt.Color(13, 110, 253));
        btnUpdateDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateDoc.setText("Update Doctor");
        pnlDoctors.add(btnUpdateDoc);
        btnUpdateDoc.setBounds(290, 530, 120, 30);

        btnRemoveDoc.setBackground(new java.awt.Color(220, 53, 69));
        btnRemoveDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveDoc.setText("Deactivate Doctor");
        pnlDoctors.add(btnRemoveDoc);
        btnRemoveDoc.setBounds(460, 530, 140, 30);

        btnRefreshDoc.setBackground(new java.awt.Color(224, 224, 224));
        btnRefreshDoc.setText("Refresh");
        pnlDoctors.add(btnRefreshDoc);
        btnRefreshDoc.setBounds(650, 530, 100, 30);

        tabbedPane.addTab("Doctors", pnlDoctors);

        pnlDepartments.setBackground(new java.awt.Color(255, 255, 255));
        pnlDepartments.setLayout(null);

        lblSearchDept.setText("Search Department:");
        pnlDepartments.add(lblSearchDept);
        lblSearchDept.setBounds(240, 20, 120, 30);
        pnlDepartments.add(txtSearchDept);
        txtSearchDept.setBounds(370, 20, 270, 30);

        btnSearchDept.setBackground(new java.awt.Color(13, 110, 253));
        btnSearchDept.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchDept.setText("Search");
        pnlDepartments.add(btnSearchDept);
        btnSearchDept.setBounds(670, 20, 100, 30);

        tblDepartments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department ID", "Department Name", "Head Doctor", "Total Doctors", "Status"
            }
        ));
        jspDepartments.setViewportView(tblDepartments);

        pnlDepartments.add(jspDepartments);
        jspDepartments.setBounds(120, 80, 800, 250);

        pnlDeptDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlDeptDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Department Details"));
        pnlDeptDetails.setLayout(null);

        lblDeptName.setText("Department Name");
        pnlDeptDetails.add(lblDeptName);
        lblDeptName.setBounds(20, 30, 120, 20);
        pnlDeptDetails.add(txtDeptName);
        txtDeptName.setBounds(140, 30, 200, 26);

        lblDeptHeadDoctor.setText("Head Doctor");
        pnlDeptDetails.add(lblDeptHeadDoctor);
        lblDeptHeadDoctor.setBounds(400, 30, 90, 20);
        pnlDeptDetails.add(txtDeptHeadDoctor);
        txtDeptHeadDoctor.setBounds(500, 30, 200, 26);

        lblDeptStatus.setText("Status");
        pnlDeptDetails.add(lblDeptStatus);
        lblDeptStatus.setBounds(20, 70, 120, 20);

        cmbDeptStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Deactive" }));
        pnlDeptDetails.add(cmbDeptStatus);
        cmbDeptStatus.setBounds(140, 70, 200, 26);

        pnlDepartments.add(pnlDeptDetails);
        pnlDeptDetails.setBounds(120, 360, 800, 140);

        btnAddDept.setBackground(new java.awt.Color(13, 110, 253));
        btnAddDept.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDept.setText("Add Department");
        pnlDepartments.add(btnAddDept);
        btnAddDept.setBounds(160, 540, 140, 40);

        btnUpdateDept.setBackground(new java.awt.Color(13, 110, 253));
        btnUpdateDept.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateDept.setText("Update Department");
        pnlDepartments.add(btnUpdateDept);
        btnUpdateDept.setBounds(310, 550, 150, 30);

        btnRemoveDept.setBackground(new java.awt.Color(220, 53, 69));
        btnRemoveDept.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveDept.setText("Deactivate Department");
        pnlDepartments.add(btnRemoveDept);
        btnRemoveDept.setBounds(490, 550, 150, 30);

        btnRefreshDept.setBackground(new java.awt.Color(224, 224, 224));
        btnRefreshDept.setText("Refresh");
        btnRefreshDept.addActionListener(this::btnRefreshDeptActionPerformed);
        pnlDepartments.add(btnRefreshDept);
        btnRefreshDept.setBounds(720, 540, 100, 40);

        tabbedPane.addTab("Departments", pnlDepartments);

        topBarPanel.setBackground(new java.awt.Color(255, 255, 255));

        pageTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        pageTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        pageTitleLabel.setText("ManageDoctor&Department");

        adminCircleLabel.setBackground(new java.awt.Color(0, 102, 204));
        adminCircleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adminCircleLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminCircleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminCircleLabel.setText("Ad");
        adminCircleLabel.setOpaque(true);
        adminCircleLabel.setPreferredSize(new java.awt.Dimension(38, 38));

        adminNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adminNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        adminNameLabel.setText("Admin");

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pageTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 624, Short.MAX_VALUE)
                .addComponent(adminCircleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(adminNameLabel)
                .addGap(24, 24, 24))
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageTitleLabel)
                    .addComponent(adminCircleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNameLabel))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshDeptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminCircleLabel;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JButton btnAddDept;
    private javax.swing.JButton btnAddDoc;
    private javax.swing.JButton btnRefreshDept;
    private javax.swing.JButton btnRefreshDoc;
    private javax.swing.JButton btnRemoveDept;
    private javax.swing.JButton btnRemoveDoc;
    private javax.swing.JButton btnSearchDept;
    private javax.swing.JButton btnSearchDoc;
    private javax.swing.JButton btnUpdateDept;
    private javax.swing.JButton btnUpdateDoc;
    private javax.swing.JComboBox<String> cmbDeptStatus;
    private javax.swing.JComboBox<String> cmbDocAvailability;
    private javax.swing.JComboBox<String> cmbDocStatus;
    private javax.swing.JScrollPane jspDepartments;
    private javax.swing.JScrollPane jspDoctors;
    private javax.swing.JLabel lblDeptHeadDoctor;
    private javax.swing.JLabel lblDeptName;
    private javax.swing.JLabel lblDeptStatus;
    private javax.swing.JLabel lblDocAvailability;
    private javax.swing.JLabel lblDocDepartment;
    private javax.swing.JLabel lblDocFullName;
    private javax.swing.JLabel lblDocPhone;
    private javax.swing.JLabel lblDocSpecialty;
    private javax.swing.JLabel lblDocStatus;
    private javax.swing.JLabel lblSearchDept;
    private javax.swing.JLabel lblSearchDoc;
    private javax.swing.JLabel pageTitleLabel;
    private javax.swing.JPanel pnlDepartments;
    private javax.swing.JPanel pnlDeptDetails;
    private javax.swing.JPanel pnlDoctorDetails;
    private javax.swing.JPanel pnlDoctors;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblDepartments;
    private javax.swing.JTable tblDoctors;
    private javax.swing.JPanel topBarPanel;
    private javax.swing.JTextField txtDeptHeadDoctor;
    private javax.swing.JTextField txtDeptName;
    private javax.swing.JTextField txtDocDepartment;
    private javax.swing.JTextField txtDocFullName;
    private javax.swing.JTextField txtDocPhone;
    private javax.swing.JTextField txtDocSpecialty;
    private javax.swing.JTextField txtSearchDept;
    private javax.swing.JTextField txtSearchDoc;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JComboBox<String> cmbFilterDepartment;
    private javax.swing.JComboBox<String> cmbFilterAvailability;
    private javax.swing.JComboBox<String> cmbFilterStatus;

    private void fixLayout() {
        lblSearchDoc.setBounds(80, 40, 100, 30);
        txtSearchDoc.setBounds(180, 40, 150, 30);
        
        javax.swing.JLabel lblDept = new javax.swing.JLabel("Dept:");
        lblDept.setBounds(340, 40, 40, 30);
        pnlDoctors.add(lblDept);
        
        cmbFilterDepartment = new javax.swing.JComboBox<>(new String[] { "All", "Cardiology", "Neurology", "Orthopedics", "General Medicine", "Pediatrics" });
        cmbFilterDepartment.setBounds(380, 40, 140, 30);
        pnlDoctors.add(cmbFilterDepartment);
        
        javax.swing.JLabel lblAvail = new javax.swing.JLabel("Avail:");
        lblAvail.setBounds(530, 40, 40, 30);
        pnlDoctors.add(lblAvail);
        
        cmbFilterAvailability = new javax.swing.JComboBox<>(new String[] { "All", "Available", "Unavailable" });
        cmbFilterAvailability.setBounds(570, 40, 100, 30);
        pnlDoctors.add(cmbFilterAvailability);
        
        javax.swing.JLabel lblStat = new javax.swing.JLabel("Status:");
        lblStat.setBounds(680, 40, 45, 30);
        pnlDoctors.add(lblStat);
        
        cmbFilterStatus = new javax.swing.JComboBox<>(new String[] { "All", "Active", "Deactive" });
        cmbFilterStatus.setBounds(725, 40, 85, 30);
        pnlDoctors.add(cmbFilterStatus);
        
        btnSearchDoc.setVisible(false);
    }

// Doctor getters
public javax.swing.JComboBox<String> getCmbFilterDepartment() { return cmbFilterDepartment; }
public javax.swing.JComboBox<String> getCmbFilterAvailability() { return cmbFilterAvailability; }
public javax.swing.JComboBox<String> getCmbFilterStatus() { return cmbFilterStatus; }

public javax.swing.JTable getTblDoctors()               { return tblDoctors; }
public javax.swing.JTextField getTxtSearchDoc()         { return txtSearchDoc; }
public javax.swing.JTextField getTxtDocFullName()       { return txtDocFullName; }
public javax.swing.JTextField getTxtDocPhone()          { return txtDocPhone; }
public javax.swing.JTextField getTxtDocSpecialty()      { return txtDocSpecialty; }
public javax.swing.JTextField getTxtDocDepartment()     { return txtDocDepartment; }
public javax.swing.JComboBox<String> getCmbDocAvailability() { return cmbDocAvailability; }
public javax.swing.JComboBox<String> getCmbDocStatus()  { return cmbDocStatus; }
public javax.swing.JButton getBtnSearchDoc()            { return btnSearchDoc; }
public javax.swing.JButton getBtnAddDoc()               { return btnAddDoc; }
public javax.swing.JButton getBtnUpdateDoc()            { return btnUpdateDoc; }
public javax.swing.JButton getBtnRemoveDoc()            { return btnRemoveDoc; }
public javax.swing.JButton getBtnRefreshDoc()           { return btnRefreshDoc; }

// Department getters
public javax.swing.JTable getTblDepartments()           { return tblDepartments; }
public javax.swing.JTextField getTxtSearchDept()        { return txtSearchDept; }
public javax.swing.JTextField getTxtDeptName()          { return txtDeptName; }
public javax.swing.JTextField getTxtDeptHeadDoctor()    { return txtDeptHeadDoctor; }
public javax.swing.JComboBox<String> getCmbDeptStatus() { return cmbDeptStatus; }
public javax.swing.JButton getBtnSearchDept()           { return btnSearchDept; }
public javax.swing.JButton getBtnAddDept()              { return btnAddDept; }
public javax.swing.JButton getBtnUpdateDept()           { return btnUpdateDept; }
public javax.swing.JButton getBtnRemoveDept()           { return btnRemoveDept; }
public javax.swing.JButton getBtnRefreshDept()          { return btnRefreshDept; }

}

