/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author aanishparajuli
 */
public class ManageuserPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageuserPanel
     */
    public ManageuserPanel() {
        initComponents();
        fixLayout();
    }

    private void fixLayout() {
        this.setLayout(new java.awt.BorderLayout());
        this.removeAll();
        this.add(topBarPanel, java.awt.BorderLayout.NORTH);
        
        // Create a responsive body layout
        javax.swing.JPanel bodyPanel = new javax.swing.JPanel(new java.awt.BorderLayout(20, 20));
        bodyPanel.setBackground(new java.awt.Color(235, 240, 251));
        bodyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        // 1. Search Bar (Top)
        javax.swing.JPanel searchPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
        searchPanel.setBackground(new java.awt.Color(235, 240, 251));
        searchPanel.add(lblSearch);
        txtSearch.setPreferredSize(new java.awt.Dimension(150, 30));
        searchPanel.add(txtSearch);
        searchPanel.add(btnSearch);
        
        searchPanel.add(lblFilterRole);
        searchPanel.add(cmbFilterRole);
        searchPanel.add(lblFilterStatus);
        searchPanel.add(cmbFilterStatus);
        searchPanel.add(lblFilterAge);
        searchPanel.add(cmbFilterAge);
        
        // 2. Details and Buttons (Bottom)
        javax.swing.JPanel bottomPanel = new javax.swing.JPanel(new java.awt.BorderLayout(10, 10));
        bottomPanel.setBackground(new java.awt.Color(235, 240, 251));
        
        javax.swing.JPanel detailsWrapper = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        detailsWrapper.setBackground(new java.awt.Color(235, 240, 251));
        pnlDetails.setPreferredSize(new java.awt.Dimension(810, 220));
        detailsWrapper.add(pnlDetails);
        
        javax.swing.JPanel buttonsPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));
        buttonsPanel.setBackground(new java.awt.Color(235, 240, 251));
        buttonsPanel.add(btnUpdateUser);
        buttonsPanel.add(btnDeactivateUser);
        buttonsPanel.add(btnRefresh);
        
        bottomPanel.add(detailsWrapper, java.awt.BorderLayout.CENTER);
        bottomPanel.add(buttonsPanel, java.awt.BorderLayout.SOUTH);
        
        // Assemble Body
        bodyPanel.add(searchPanel, java.awt.BorderLayout.NORTH);
        bodyPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER); // Table stretches to fill space
        bodyPanel.add(bottomPanel, java.awt.BorderLayout.SOUTH);
        
        this.add(bodyPanel, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        pnlDetails = new javax.swing.JPanel();
        lblFullName = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        DOB = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        changepassword = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        lblGender = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        txtFullName1 = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        btnUpdateUser = new javax.swing.JButton();
        btnDeactivateUser = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        topBarPanel = new javax.swing.JPanel();
        pageTitleLabel = new javax.swing.JLabel();
        adminCircleLabel = new javax.swing.JLabel();
        adminNameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lblSearch.setText("Search User:");
        jPanel1.add(lblSearch);
        lblSearch.setBounds(130, 140, 80, 30);
        jPanel1.add(txtSearch);
        txtSearch.setBounds(210, 140, 200, 30);

        btnSearch.setBackground(new java.awt.Color(13, 110, 253));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        jPanel1.add(btnSearch);
        btnSearch.setBounds(420, 140, 80, 30);
        
        lblFilterRole = new javax.swing.JLabel("Role:");
        jPanel1.add(lblFilterRole);
        lblFilterRole.setBounds(510, 140, 40, 30);
        cmbFilterRole = new javax.swing.JComboBox<>(new String[]{"All", "Admin", "Receptionist", "Doctor", "Patient"});
        jPanel1.add(cmbFilterRole);
        cmbFilterRole.setBounds(550, 140, 100, 30);
        
        lblFilterStatus = new javax.swing.JLabel("Status:");
        jPanel1.add(lblFilterStatus);
        lblFilterStatus.setBounds(660, 140, 40, 30);
        cmbFilterStatus = new javax.swing.JComboBox<>(new String[]{"All", "Active", "Deactive"});
        jPanel1.add(cmbFilterStatus);
        cmbFilterStatus.setBounds(700, 140, 90, 30);
        
        lblFilterAge = new javax.swing.JLabel("Age:");
        jPanel1.add(lblFilterAge);
        lblFilterAge.setBounds(800, 140, 30, 30);
        cmbFilterAge = new javax.swing.JComboBox<>(new String[]{"All", "Under 18", "18-35", "36-50", "50+"});
        jPanel1.add(cmbFilterAge);
        cmbFilterAge.setBounds(830, 140, 110, 30);

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Full Name", "Phone", "Gender", "Date of Birth", "Role", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 190, 810, 270);

        pnlDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected User Details"));
        pnlDetails.setLayout(null);

        lblFullName.setText("Full Name");
        pnlDetails.add(lblFullName);
        lblFullName.setBounds(20, 30, 70, 20);
        pnlDetails.add(password);
        password.setBounds(120, 160, 200, 26);

        DOB.setText("Date of birth");
        pnlDetails.add(DOB);
        DOB.setBounds(350, 30, 100, 20);
        pnlDetails.add(txtEmail);
        txtEmail.setBounds(460, 30, 200, 26);

        changepassword.setText("Change Password");
        pnlDetails.add(changepassword);
        changepassword.setBounds(10, 160, 110, 20);

        lblBloodGroup = new javax.swing.JLabel();
        cmbBloodGroup = new javax.swing.JComboBox<>();
        lblBloodGroup.setText("Blood Group");
        pnlDetails.add(lblBloodGroup);
        lblBloodGroup.setBounds(350, 160, 100, 20);
        cmbBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", "Unknown" }));
        pnlDetails.add(cmbBloodGroup);
        cmbBloodGroup.setBounds(460, 160, 200, 26);
        pnlDetails.add(txtPhone);
        txtPhone.setBounds(100, 70, 200, 26);

        lblRole.setText("System Role");
        pnlDetails.add(lblRole);
        lblRole.setBounds(350, 70, 100, 20);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Receptionist", "Patient" }));
        pnlDetails.add(cmbRole);
        cmbRole.setBounds(460, 70, 200, 26);

        lblGender.setText("Gender");
        pnlDetails.add(lblGender);
        lblGender.setBounds(20, 110, 70, 20);

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        pnlDetails.add(cmbGender);
        cmbGender.setBounds(100, 110, 200, 26);

        lblStatus.setText("Status");
        pnlDetails.add(lblStatus);
        lblStatus.setBounds(350, 110, 100, 20);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Deactive" }));
        pnlDetails.add(cmbStatus);
        cmbStatus.setBounds(460, 110, 200, 26);
        pnlDetails.add(txtFullName1);
        txtFullName1.setBounds(100, 30, 200, 26);

        lblPhone1.setText("Phone");
        pnlDetails.add(lblPhone1);
        lblPhone1.setBounds(20, 70, 70, 20);

        jPanel1.add(pnlDetails);
        pnlDetails.setBounds(130, 500, 810, 220);

        btnUpdateUser.setBackground(new java.awt.Color(13, 110, 253));
        btnUpdateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUser.setText("Update User");
        jPanel1.add(btnUpdateUser);
        btnUpdateUser.setBounds(310, 770, 120, 40);

        btnDeactivateUser.setBackground(new java.awt.Color(220, 53, 69));
        btnDeactivateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnDeactivateUser.setText("Deactivate User");
        jPanel1.add(btnDeactivateUser);
        btnDeactivateUser.setBounds(450, 770, 130, 40);

        btnRefresh.setBackground(new java.awt.Color(224, 224, 224));
        btnRefresh.setText("Refresh");
        jPanel1.add(btnRefresh);
        btnRefresh.setBounds(600, 770, 140, 40);

        topBarPanel.setBackground(new java.awt.Color(255, 255, 255));

        pageTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        pageTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        pageTitleLabel.setText("ManageUsers");

        adminCircleLabel.setBackground(new java.awt.Color(0, 102, 204));
        adminCircleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adminCircleLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminCircleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminCircleLabel.setText("Ad");
        adminCircleLabel.setOpaque(true);
        adminCircleLabel.setPreferredSize(new java.awt.Dimension(38, 38));

        adminNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adminNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        adminNameLabel.setText("Admin");

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pageTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminCircleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(adminNameLabel)
                .addGap(24, 24, 24))
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageTitleLabel)
                    .addComponent(adminCircleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNameLabel))
                .addGap(14, 14, 14))
        );

        jPanel1.add(topBarPanel);
        topBarPanel.setBounds(10, 10, 1160, 58);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1175, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel adminCircleLabel;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JButton btnDeactivateUser;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JLabel changepassword;
    private javax.swing.JComboBox<String> cmbBloodGroup;
    private javax.swing.JComboBox<String> cmbFilterAge;
    private javax.swing.JComboBox<String> cmbFilterRole;
    private javax.swing.JComboBox<String> cmbFilterStatus;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblFilterAge;
    private javax.swing.JLabel lblFilterRole;
    private javax.swing.JLabel lblFilterStatus;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel pageTitleLabel;
    private javax.swing.JTextField password;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JTable tblUsers;
    private javax.swing.JPanel topBarPanel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

public javax.swing.JButton getBtnSearch()        { return btnSearch; }
public javax.swing.JButton getBtnUpdateUser()    { return btnUpdateUser; }
public javax.swing.JButton getBtnDeactivateUser(){ return btnDeactivateUser; }
public javax.swing.JButton getBtnRefresh()       { return btnRefresh; }
public javax.swing.JTextField getTxtSearch()     { return txtSearch; }
public javax.swing.JComboBox<String> getCmbFilterRole() { return cmbFilterRole; }
public javax.swing.JComboBox<String> getCmbFilterStatus() { return cmbFilterStatus; }
public javax.swing.JComboBox<String> getCmbFilterAge() { return cmbFilterAge; }
public javax.swing.JTextField getTxtFullName()       { return txtFullName1; }
public javax.swing.JTextField getTxtPhone()      { return txtPhone; }
public javax.swing.JTextField getTxtDob() { return txtEmail; }
public javax.swing.JComboBox<String> getCmbRole()  { return cmbRole; }
public javax.swing.JComboBox<String> getCmbStatus(){ return cmbStatus; }
public javax.swing.JComboBox<String> getCmbGender(){ return cmbGender; }
public javax.swing.JTable getTblUsers()          { return tblUsers; }
public javax.swing.JTextField getTxtChangePassword() { return password; } 
public javax.swing.JComboBox<String> getCmbBloodGroup(){ return cmbBloodGroup; }
}
