/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author aanishparajuli
 */
public class NotificationPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotificationPanel
     */
    private javax.swing.JTable notificationTable;

    public NotificationPanel() {
        initComponents();
        setupTable();
        
        // --- Apply UI Standardization ---
        java.awt.Color bodyBg = new java.awt.Color(235, 240, 251);
        this.setBackground(bodyBg);
        mainContentPanel.setBackground(bodyBg);
        topBarPanel1.setPreferredSize(new java.awt.Dimension(1000, 60));
        topBarPanel1.setMinimumSize(new java.awt.Dimension(100, 60));
    }

    private void setupTable() {
        this.setLayout(new java.awt.BorderLayout());
        this.removeAll();
        this.add(topBarPanel1, java.awt.BorderLayout.NORTH);
        this.add(mainContentPanel, java.awt.BorderLayout.CENTER);

        mainContentPanel.removeAll();
        mainContentPanel.setLayout(new java.awt.BorderLayout(15, 15));
        mainContentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        
        scheduleCardPanel.removeAll();
        scheduleCardPanel.setLayout(new java.awt.BorderLayout(0, 15));
        
        scheduleTitleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 0, 0));
        scheduleCardPanel.add(scheduleTitleLabel, java.awt.BorderLayout.NORTH);
        
        notificationTable = new javax.swing.JTable();
        notificationTable.setRowHeight(30);
        notificationTable.setFont(new java.awt.Font("Helvetica Neue", 0, 14));
        notificationTable.getTableHeader().setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 14));
        
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(notificationTable);
        scrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 15, 15));
        
        scheduleCardPanel.add(scrollPane, java.awt.BorderLayout.CENTER);
        mainContentPanel.add(scheduleCardPanel, java.awt.BorderLayout.CENTER);
        
        mainContentPanel.revalidate();
        mainContentPanel.repaint();
    }

    public javax.swing.JTable getNotificationTable() {
        return notificationTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBarPanel1 = new javax.swing.JPanel();
        pageTitleLabel1 = new javax.swing.JLabel();
        adminCircleLabel1 = new javax.swing.JLabel();
        adminNameLabel1 = new javax.swing.JLabel();
        mainContentPanel = new javax.swing.JPanel();
        scheduleCardPanel = new javax.swing.JPanel();
        scheduleTitleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        topBarPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pageTitleLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        pageTitleLabel1.setForeground(new java.awt.Color(0, 102, 204));
        pageTitleLabel1.setText("Notification");

        adminCircleLabel1.setBackground(new java.awt.Color(0, 102, 204));
        adminCircleLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adminCircleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        adminCircleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminCircleLabel1.setText("Ad");
        adminCircleLabel1.setOpaque(true);
        adminCircleLabel1.setPreferredSize(new java.awt.Dimension(38, 38));

        adminNameLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adminNameLabel1.setForeground(new java.awt.Color(51, 51, 51));
        adminNameLabel1.setText("Admin");

        javax.swing.GroupLayout topBarPanel1Layout = new javax.swing.GroupLayout(topBarPanel1);
        topBarPanel1.setLayout(topBarPanel1Layout);
        topBarPanel1Layout.setHorizontalGroup(
            topBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pageTitleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1044, Short.MAX_VALUE)
                .addComponent(adminCircleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(adminNameLabel1)
                .addGap(24, 24, 24))
        );
        topBarPanel1Layout.setVerticalGroup(
            topBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(topBarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageTitleLabel1)
                    .addComponent(adminCircleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNameLabel1))
                .addGap(14, 14, 14))
        );

        mainContentPanel.setBackground(new java.awt.Color(255, 255, 255));

        scheduleCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        scheduleCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scheduleTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        scheduleTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        scheduleTitleLabel.setText("Recent notifications");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("  👤");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("New Patient anmol registered sucessfully.");

        jLabel3.setText("2 minutes ago");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("✓");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Appointment Confirmed for Dr.sharma at 09:00AM.");

        jLabel6.setText("12 minutes ago");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setText("⚠️");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setText("Patient Ram's fees payment is overdue.");

        jLabel9.setText("1 hour ago");

        javax.swing.GroupLayout scheduleCardPanelLayout = new javax.swing.GroupLayout(scheduleCardPanel);
        scheduleCardPanel.setLayout(scheduleCardPanelLayout);
        scheduleCardPanelLayout.setHorizontalGroup(
            scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                        .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(scheduleTitleLabel))
                            .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 574, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scheduleCardPanelLayout.setVerticalGroup(
            scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleCardPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scheduleTitleLabel)
                .addGap(52, 52, 52)
                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(scheduleCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainContentPanelLayout = new javax.swing.GroupLayout(mainContentPanel);
        mainContentPanel.setLayout(mainContentPanelLayout);
        mainContentPanelLayout.setHorizontalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scheduleCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainContentPanelLayout.setVerticalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scheduleCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(topBarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(topBarPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(301, 301, 301))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminCircleLabel1;
    private javax.swing.JLabel adminNameLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JLabel pageTitleLabel1;
    private javax.swing.JPanel scheduleCardPanel;
    private javax.swing.JLabel scheduleTitleLabel;
    private javax.swing.JPanel topBarPanel1;
    // End of variables declaration//GEN-END:variables

public javax.swing.JLabel getJLabel2() { return jLabel2; }
public javax.swing.JLabel getJLabel3() { return jLabel3; }
public javax.swing.JLabel getJLabel5() { return jLabel5; }
public javax.swing.JLabel getJLabel6() { return jLabel6; }
public javax.swing.JLabel getJLabel8() { return jLabel8; }
public javax.swing.JLabel getJLabel9() { return jLabel9; }

}