/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PatientController;

/**
 *
 * @author Aakash Das
 */
public class Patients extends javax.swing.JFrame {

    private PatientController controller;

    /**
     * Creates new form Patients
     */
    public Patients() {
        initComponents();
        controller = new PatientController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnBookAppointment = new javax.swing.JButton();
        btnQueue = new javax.swing.JButton();
        btnMedicalRecord = new javax.swing.JButton();
        btnRating = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                int confirm = javax.swing.JOptionPane.showConfirmDialog(Patients.this, 
                    "Are you sure you want to exit the application?", "Exit Confirmation", 
                    javax.swing.JOptionPane.YES_NO_OPTION);
                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(30, 100, 180));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("🏥 Patient Panel");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(32, 21, 160, 22);

        btnHome.setBackground(new java.awt.Color(40, 110, 190));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHome.setText("🏠 Home");
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome);
        btnHome.setBounds(20, 70, 210, 40);

        btnBookAppointment.setBackground(new java.awt.Color(40, 110, 190));
        btnBookAppointment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBookAppointment.setText("📅 Book Appointment");
        btnBookAppointment.setContentAreaFilled(false);
        jPanel1.add(btnBookAppointment);
        btnBookAppointment.setBounds(20, 120, 210, 40);

        btnQueue.setBackground(new java.awt.Color(40, 110, 190));
        btnQueue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQueue.setText("📍 My Queue Position");
        btnQueue.setContentAreaFilled(false);
        jPanel1.add(btnQueue);
        btnQueue.setBounds(20, 170, 210, 40);

        btnMedicalRecord.setBackground(new java.awt.Color(40, 110, 190));
        btnMedicalRecord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMedicalRecord.setText("📁 Medical record");
        btnMedicalRecord.setContentAreaFilled(false);
        jPanel1.add(btnMedicalRecord);
        btnMedicalRecord.setBounds(20, 220, 210, 40);

        btnRating.setBackground(new java.awt.Color(40, 110, 190));
        btnRating.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRating.setText("⭐ Give Rating");
        btnRating.setContentAreaFilled(false);
        jPanel1.add(btnRating);
        btnRating.setBounds(20, 270, 210, 40);

        btnAccount.setBackground(new java.awt.Color(40, 110, 190));
        btnAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAccount.setText("⚙️ Account");
        btnAccount.setContentAreaFilled(false);
        jPanel1.add(btnAccount);
        btnAccount.setBounds(20, 320, 210, 40);

        btnLogout.setBackground(new java.awt.Color(200, 50, 50));
        btnLogout.setContentAreaFilled(false);
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        jPanel1.add(btnLogout);
        btnLogout.setBounds(20, 620, 210, 35);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 720);

        contentPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contentPanel);
        contentPanel.setBounds(250, 0, 750, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAccount;
    public javax.swing.JButton btnBookAppointment;
    public javax.swing.JButton btnHome;
    public javax.swing.JButton btnLogout;
    public javax.swing.JButton btnMedicalRecord;
    public javax.swing.JButton btnQueue;
    public javax.swing.JButton btnRating;
    public javax.swing.JPanel contentPanel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
