/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Aakash Das
 */
public class PatientHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientHomePanel
     */
    public PatientHomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBookNow = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnViewQueue = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblNotificationBell = new javax.swing.JLabel();
        lblNotificationText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 700));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Welcome, Patient \uD83D\uDC4B");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 300, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        jLabel2.setText("\uD83C\uDFE5");
        add(jLabel2);
        jLabel2.setBounds(690, 30, 30, 30);

        lblNotificationBell.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblNotificationBell.setText("\uD83D\uDD14");
        lblNotificationBell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lblNotificationBell);
        lblNotificationBell.setBounds(650, 28, 40, 40);

        lblNotificationText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNotificationText.setForeground(new java.awt.Color(220, 50, 50)); // Red attention color
        lblNotificationText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNotificationText.setText(""); // Initially empty
        add(lblNotificationText);
        lblNotificationText.setBounds(340, 35, 300, 25);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("\uD83D\uDCC5 Book New Appointment");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 20, 250, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(120, 120, 120));
        jLabel4.setText("Schedule a new appointment with a doctor.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 50, 270, 20);

        btnBookNow.setBackground(new java.awt.Color(30, 100, 180));
        btnBookNow.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBookNow.setText("Book Now");
        jPanel1.add(btnBookNow);
        btnBookNow.setBounds(30, 90, 120, 35);

        add(jPanel1);
        jPanel1.setBounds(30, 90, 320, 150);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("\uD83D\uDCCD View My Queue");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 20, 220, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(120, 120, 120));
        jLabel6.setText("Check your current queue status.");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 50, 250, 20);

        btnViewQueue.setBackground(new java.awt.Color(34, 139, 34));
        btnViewQueue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewQueue.setText("View Queue");
        jPanel2.add(btnViewQueue);
        btnViewQueue.setBounds(30, 90, 120, 35);

        add(jPanel2);
        jPanel2.setBounds(380, 90, 320, 150);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(180, 180, 180));
        jLabel7.setText("Home");
        add(jLabel7);
        jLabel7.setBounds(5, 5, 50, 14);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookNow;
    private javax.swing.JButton btnViewQueue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblNotificationBell;
    private javax.swing.JLabel lblNotificationText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnBookNow() {
        return btnBookNow;
    }

    public javax.swing.JButton getBtnViewQueue() {
        return btnViewQueue;
    }

    public void setWelcomeName(String name) {
        jLabel1.setText("Welcome, " + name + " \uD83D\uDC4B");
    }

    public javax.swing.JLabel getLblNotificationBell() {
        return lblNotificationBell;
    }

    public javax.swing.JLabel getLblNotificationText() {
        return lblNotificationText;
    }
}
