/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Aakash Das
 */
public class QueuePanel extends javax.swing.JPanel {

    /**
     * Creates new form QueuePanel
     */
    public QueuePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 700));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("📍 My Queue Position");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 250, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        jLabel2.setText("🔔");
        add(jLabel2);
        jLabel2.setBounds(690, 30, 30, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(100, 100, 100));
        jLabel10.setText("Department:");
        add(jLabel10);
        jLabel10.setBounds(450, 100, 90, 30);

        cmbDepartment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(cmbDepartment);
        cmbDepartment.setBounds(540, 100, 140, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(120, 120, 120));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("YOUR NUMBER");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 20, 300, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 100, 180));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("7");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 50, 300, 80);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(120, 120, 120));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Estimated wait: 25 mins");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 140, 300, 20);

        add(jPanel1);
        jPanel1.setBounds(60, 150, 280, 180);

        // Waitlist No. panel (to the right of YOUR NUMBER)
        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(120, 120, 120));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TOTAL IN QUEUE");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(0, 20, 280, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(200, 100, 30));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("-");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(0, 50, 280, 80);

        add(jPanel4);
        jPanel4.setBounds(360, 150, 280, 180);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(120, 120, 120));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CURRENTLY SERVING");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 20, 330, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("3");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 40, 330, 60);

        add(jPanel2);
        jPanel2.setBounds(30, 380, 330, 120);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(120, 120, 120));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PEOPLE AHEAD");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(0, 20, 330, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("3");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(0, 40, 330, 60);

        add(jPanel3);
        jPanel3.setBounds(390, 380, 330, 120);

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(220, 53, 69));
        btnCancel.setText("Cancel Queue");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 53, 69)));
        add(btnCancel);
        btnCancel.setBounds(30, 550, 130, 40);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JComboBox<model.Department> cmbDepartment;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<model.Department> getCmbDepartment() {
        return cmbDepartment;
    }

    public javax.swing.JButton getBtnCancel() {
        return btnCancel;
    }

    public void displayQueue(model.QueueItem item) {
        jLabel4.setText(String.valueOf(item.getTokenNumber()));
        jLabel5.setText("Status: " + item.getStatus());
        
        // The actual numbers will be updated by the Controller dynamically.
        btnCancel.setVisible(true);
    }

    public void displayNoQueue() {
        jLabel4.setText("-");
        jLabel5.setText("You are not currently in any queue.");
        btnCancel.setVisible(false);
    }
    
    public void setQueueMetrics(String serving, String ahead) {
        jLabel7.setText(serving);
        jLabel9.setText(ahead);
    }

    public void setWaitlistNumber(String waitlistNo) {
        jLabel12.setText(waitlistNo);
    }
}
