/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Aakash Das
 */
public class RatingPanel extends javax.swing.JPanel {

    /**
     * Creates new form RatingPanel
     */
    public RatingPanel() {
        initComponents();
        initCustomComponents();
    }

    private javax.swing.JComboBox<Integer> cmbStars;
    private javax.swing.JComboBox<model.Appointment> cmbAppointments;

    private void initCustomComponents() {
        cmbStars = new javax.swing.JComboBox<>(new Integer[]{1, 2, 3, 4, 5});
        cmbAppointments = new javax.swing.JComboBox<>();
        
        cmbStars.setBounds(40, 100, 120, 35);
        cmbAppointments.setBounds(40, 150, 300, 35);
        cmbAppointments.setVisible(false);
        jLabel6.setBounds(40, 150, 250, 20);
        txtFeedback.setBounds(40, 180, 600, 100);
        btnSubmit.setBounds(250, 300, 180, 40);
        
        jLabel5.setVisible(false);
        
        javax.swing.JLabel lblOutOf5 = new javax.swing.JLabel("out of 5");
        lblOutOf5.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblOutOf5.setBounds(170, 100, 100, 35);
        jPanel1.add(lblOutOf5);
        
        jPanel1.add(cmbStars);
        jPanel1.add(cmbAppointments);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFeedback = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 700));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("⭐ Give Rating");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("🔔");
        add(jLabel2);
        jLabel2.setBounds(690, 30, 30, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Rate Your Experience");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 30, 200, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(100, 100, 100));
        jLabel4.setText("Please rate your experience with our service.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 60, 300, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 165, 0));
        jLabel5.setText("⭐ ⭐ ⭐ ⭐ ⭐");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 110, 300, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(100, 100, 100));
        jLabel6.setText("Write your feedback (optional)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 180, 250, 20);

        txtFeedback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFeedback.setText("Great service and very helpful staff!");
        jPanel1.add(txtFeedback);
        txtFeedback.setBounds(40, 210, 600, 100);

        btnSubmit.setBackground(new java.awt.Color(30, 100, 180));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(51, 51, 51));
        btnSubmit.setText("Submit Rating");
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(250, 350, 180, 40);

        add(jPanel1);
        jPanel1.setBounds(30, 90, 680, 430);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFeedback;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<Integer> getCmbStars() {
        return cmbStars;
    }

    public javax.swing.JComboBox<model.Appointment> getCmbAppointments() {
        return cmbAppointments;
    }

    public javax.swing.JTextField getTxtFeedback() {
        return txtFeedback;
    }

    public javax.swing.JButton getBtnSubmit() {
        return btnSubmit;
    }
}
