/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author aanishparajuli
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();
        fixLayout();
    }

    private void fixLayout() {
        summaryCardPanel.setLayout(new java.awt.BorderLayout());
        summaryCardPanel.removeAll();
        
        javax.swing.JPanel topBar = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        topBar.setBackground(java.awt.Color.WHITE);
        topBar.add(lblSearch);
        topBar.add(txtSearch);
        topBar.add(btnSearch);
        
        javax.swing.JPanel titlePanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        titlePanel.setBackground(java.awt.Color.WHITE);
        titlePanel.add(summaryTitleLabel);
        
        javax.swing.JPanel headerPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        headerPanel.add(titlePanel, java.awt.BorderLayout.NORTH);
        headerPanel.add(topBar, java.awt.BorderLayout.CENTER);
        
        summaryCardPanel.add(headerPanel, java.awt.BorderLayout.NORTH);
        summaryCardPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBarPanel = new javax.swing.JPanel();
        pageTitleLabel = new javax.swing.JLabel();
        adminCircleLabel = new javax.swing.JLabel();
        adminNameLabel = new javax.swing.JLabel();
        mainContentPanel = new javax.swing.JPanel();
        cardsRowPanel = new javax.swing.JPanel();
        rcard1Panel4 = new javax.swing.JPanel();
        rcard1NumberLabel4 = new javax.swing.JLabel();
        rcard1TextLabel4 = new javax.swing.JLabel();
        rcard2Panel = new javax.swing.JPanel();
        rcard2NumberLabel = new javax.swing.JLabel();
        rcard2TextLabel = new javax.swing.JLabel();
        rcard3Panel = new javax.swing.JPanel();
        rcard3NumberLabel = new javax.swing.JLabel();
        rcard3TextLabel = new javax.swing.JLabel();
        rcard4Panel = new javax.swing.JPanel();
        rcard4NumberLabel = new javax.swing.JLabel();
        rcard4TextLabel = new javax.swing.JLabel();
        summaryCardPanel = new javax.swing.JPanel();
        summaryTitleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        topBarPanel.setBackground(new java.awt.Color(255, 255, 255));

        pageTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        pageTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        pageTitleLabel.setText("Report");

        adminCircleLabel.setBackground(new java.awt.Color(0, 102, 204));
        adminCircleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adminCircleLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminCircleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminCircleLabel.setText("Ad");
        adminCircleLabel.setOpaque(true);
        adminCircleLabel.setPreferredSize(new java.awt.Dimension(38, 38));

        adminNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adminNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        adminNameLabel.setText("Admin");

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pageTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 928, Short.MAX_VALUE)
                .addComponent(adminCircleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(adminNameLabel)
                .addGap(24, 24, 24))
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageTitleLabel)
                    .addComponent(adminCircleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNameLabel))
                .addGap(14, 14, 14))
        );

        mainContentPanel.setBackground(new java.awt.Color(235, 240, 251));

        cardsRowPanel.setBackground(new java.awt.Color(235, 240, 251));

        rcard1Panel4.setBackground(new java.awt.Color(30, 90, 200));

        rcard1NumberLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        rcard1NumberLabel4.setForeground(new java.awt.Color(255, 255, 255));
        rcard1NumberLabel4.setText("48");

        rcard1TextLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        rcard1TextLabel4.setForeground(new java.awt.Color(210, 228, 255));
        rcard1TextLabel4.setText("Visits this month");

        javax.swing.GroupLayout rcard1Panel4Layout = new javax.swing.GroupLayout(rcard1Panel4);
        rcard1Panel4.setLayout(rcard1Panel4Layout);
        rcard1Panel4Layout.setHorizontalGroup(
            rcard1Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rcard1Panel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(rcard1Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rcard1NumberLabel4)
                    .addComponent(rcard1TextLabel4))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        rcard1Panel4Layout.setVerticalGroup(
            rcard1Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rcard1Panel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rcard1NumberLabel4)
                .addGap(6, 6, 6)
                .addComponent(rcard1TextLabel4)
                .addGap(20, 20, 20))
        );

        rcard2Panel.setBackground(new java.awt.Color(30, 120, 220));

        rcard2NumberLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        rcard2NumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        rcard2NumberLabel.setText("5");

        rcard2TextLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        rcard2TextLabel.setForeground(new java.awt.Color(210, 228, 255));
        rcard2TextLabel.setText("Total Doctor");

        javax.swing.GroupLayout rcard2PanelLayout = new javax.swing.GroupLayout(rcard2Panel);
        rcard2Panel.setLayout(rcard2PanelLayout);
        rcard2PanelLayout.setHorizontalGroup(
            rcard2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rcard2PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(rcard2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rcard2NumberLabel)
                    .addComponent(rcard2TextLabel))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        rcard2PanelLayout.setVerticalGroup(
            rcard2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rcard2PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rcard2NumberLabel)
                .addGap(6, 6, 6)
                .addComponent(rcard2TextLabel)
                .addGap(20, 20, 20))
        );

        rcard3Panel.setBackground(new java.awt.Color(51, 153, 255));

        rcard3NumberLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        rcard3NumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        rcard3NumberLabel.setText("15");

        rcard3TextLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        rcard3TextLabel.setForeground(new java.awt.Color(210, 228, 255));
        rcard3TextLabel.setText("Appointment this month");

        javax.swing.GroupLayout rcard3PanelLayout = new javax.swing.GroupLayout(rcard3Panel);
        rcard3Panel.setLayout(rcard3PanelLayout);
        rcard3PanelLayout.setHorizontalGroup(
            rcard3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rcard3PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(rcard3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rcard3NumberLabel)
                    .addComponent(rcard3TextLabel))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        rcard3PanelLayout.setVerticalGroup(
            rcard3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rcard3PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rcard3NumberLabel)
                .addGap(6, 6, 6)
                .addComponent(rcard3TextLabel)
                .addGap(20, 20, 20))
        );

        rcard4Panel.setBackground(new java.awt.Color(100, 180, 255));

        rcard4NumberLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        rcard4NumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        rcard4NumberLabel.setText("3");

        rcard4TextLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        rcard4TextLabel.setForeground(new java.awt.Color(210, 228, 255));
        rcard4TextLabel.setText("Department");

        javax.swing.GroupLayout rcard4PanelLayout = new javax.swing.GroupLayout(rcard4Panel);
        rcard4Panel.setLayout(rcard4PanelLayout);
        rcard4PanelLayout.setHorizontalGroup(
            rcard4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rcard4PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(rcard4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rcard4NumberLabel)
                    .addComponent(rcard4TextLabel))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        rcard4PanelLayout.setVerticalGroup(
            rcard4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rcard4PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rcard4NumberLabel)
                .addGap(6, 6, 6)
                .addComponent(rcard4TextLabel)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout cardsRowPanelLayout = new javax.swing.GroupLayout(cardsRowPanel);
        cardsRowPanel.setLayout(cardsRowPanelLayout);
        cardsRowPanelLayout.setHorizontalGroup(
            cardsRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardsRowPanelLayout.createSequentialGroup()
                .addComponent(rcard1Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(rcard2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(rcard3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(rcard4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardsRowPanelLayout.setVerticalGroup(
            cardsRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rcard1Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rcard2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rcard3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rcard4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        summaryCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        summaryCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        summaryTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        summaryTitleLabel.setForeground(new java.awt.Color(0, 102, 204));
        summaryTitleLabel.setText("Monthly summary");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"abc", "       cardiology", "active", "  12 may", "Dr.xyz"},
                {"gggx", "ndddxb", "bxbx", "bxbx", "xbx"},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Department", "Status", "Visit_Date", "Doctor Assigned"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        lblSearch.setText("Search User:");

        btnSearch.setBackground(new java.awt.Color(13, 110, 253));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");

        javax.swing.GroupLayout summaryCardPanelLayout = new javax.swing.GroupLayout(summaryCardPanel);
        summaryCardPanel.setLayout(summaryCardPanelLayout);
        summaryCardPanelLayout.setHorizontalGroup(
            summaryCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryCardPanelLayout.createSequentialGroup()
                .addGroup(summaryCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summaryCardPanelLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(summaryTitleLabel))
                    .addGroup(summaryCardPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(summaryCardPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        summaryCardPanelLayout.setVerticalGroup(
            summaryCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(summaryTitleLabel)
                .addGap(106, 106, 106)
                .addGroup(summaryCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainContentPanelLayout = new javax.swing.GroupLayout(mainContentPanel);
        mainContentPanel.setLayout(mainContentPanelLayout);
        mainContentPanelLayout.setHorizontalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardsRowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(summaryCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        mainContentPanelLayout.setVerticalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cardsRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(summaryCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainContentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminCircleLabel;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel cardsRowPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JLabel pageTitleLabel;
    private javax.swing.JLabel rcard1NumberLabel4;
    private javax.swing.JPanel rcard1Panel4;
    private javax.swing.JLabel rcard1TextLabel4;
    private javax.swing.JLabel rcard2NumberLabel;
    private javax.swing.JPanel rcard2Panel;
    private javax.swing.JLabel rcard2TextLabel;
    private javax.swing.JLabel rcard3NumberLabel;
    private javax.swing.JPanel rcard3Panel;
    private javax.swing.JLabel rcard3TextLabel;
    private javax.swing.JLabel rcard4NumberLabel;
    private javax.swing.JPanel rcard4Panel;
    private javax.swing.JLabel rcard4TextLabel;
    private javax.swing.JPanel summaryCardPanel;
    private javax.swing.JLabel summaryTitleLabel;
    private javax.swing.JPanel topBarPanel;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

public javax.swing.JLabel getRcard1NumberLabel() { return rcard1NumberLabel4; }
public javax.swing.JLabel getRcard2NumberLabel() { return rcard2NumberLabel; }
public javax.swing.JLabel getRcard3NumberLabel() { return rcard3NumberLabel; }
public javax.swing.JLabel getRcard4NumberLabel() { return rcard4NumberLabel; }
public javax.swing.JTable getJTable1()           { return jTable1; }
public javax.swing.JTextField getSearchField() { return txtSearch; }
public javax.swing.JButton getSearchButton()   { return btnSearch; }
}