/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dell
 */
public class WithTabbedPane extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WithTabbedPane.class.getName());

    /**
     * Creates new form With
     */
    public WithTabbedPane() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Make it full screen
        setupTabs();
    }

    private controller.DashboardController dashboardController;
    private controller.RegisterWalkinController registerWalkinController;
    private controller.GenerateTokenController generateTokenController;
    private controller.AssignToDoctorController assignToDoctorController;

    public controller.DashboardController getDashboardController() { return dashboardController; }
    public controller.RegisterWalkinController getRegisterWalkinController() { return registerWalkinController; }
    public controller.GenerateTokenController getGenerateTokenController() { return generateTokenController; }
    public controller.AssignToDoctorController getAssignToDoctorController() { return assignToDoctorController; }

    public void switchToTab(int index) { jTabbedPane1.setSelectedIndex(index); }

    private void setupTabs() {
        // Change layout to BorderLayout to align full page at runtime
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(sidebarPanel, java.awt.BorderLayout.WEST);
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        // The components are added via GUI Builder to jTabbedPane1 directly
        
        dashboardController = new controller.DashboardController(jPanel1, this);
        registerWalkinController = new controller.RegisterWalkinController(jPanel2, this);
        generateTokenController = new controller.GenerateTokenController(jPanel3, this);
        assignToDoctorController = new controller.AssignToDoctorController(jPanel4, this);
        
        btnManageWaitlist1.setVisible(true);
        btnManageWaitlist1.addActionListener(e -> jTabbedPane1.setSelectedIndex(0));
        
        btnRegisterWalkin.addActionListener(e -> jTabbedPane1.setSelectedIndex(1));
        btnGenerateToken.addActionListener(e -> jTabbedPane1.setSelectedIndex(2));
        btnAssignDoctor.addActionListener(e -> jTabbedPane1.setSelectedIndex(3));
        
        btnLogout.addActionListener(e -> {
            int option = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to log out?",
                    "Logout",
                    javax.swing.JOptionPane.YES_NO_OPTION
            );
            if (option == javax.swing.JOptionPane.YES_OPTION) {
                this.dispose();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        lblHospicare = new javax.swing.JLabel();
        btnRegisterWalkin = new javax.swing.JButton();
        btnGenerateToken = new javax.swing.JButton();
        btnAssignDoctor = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnManageWaitlist1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new view.DashboardView();
        jPanel2 = new view.RegisterWalkinView();
        jPanel3 = new view.GenerateTokenView();
        jPanel4 = new view.AssignToDoctorView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(22, 137, 176));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(240, 700));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHospicare.setForeground(new java.awt.Color(255, 255, 255));
        lblHospicare.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHospicare.setText("HOSPICARE");
        sidebarPanel.add(lblHospicare, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnRegisterWalkin.setBackground(new java.awt.Color(18, 116, 210));
        btnRegisterWalkin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterWalkin.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterWalkin.setText("Register Walk-in");
        btnRegisterWalkin.setBorderPainted(false);
        btnRegisterWalkin.setFocusPainted(false);
        btnRegisterWalkin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegisterWalkin.setOpaque(true);
        sidebarPanel.add(btnRegisterWalkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 107, 210, 37));

        btnGenerateToken.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGenerateToken.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateToken.setText("Generate Token");
        btnGenerateToken.setBorderPainted(false);
        btnGenerateToken.setContentAreaFilled(false);
        btnGenerateToken.setFocusPainted(false);
        btnGenerateToken.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnGenerateToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 154, 210, 37));

        btnAssignDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignDoctor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssignDoctor.setText("Assign to Doctor");
        btnAssignDoctor.setBorderPainted(false);
        btnAssignDoctor.setContentAreaFilled(false);
        btnAssignDoctor.setFocusPainted(false);
        btnAssignDoctor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnAssignDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 201, 210, 37));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 100, 100));
        btnLogout.setText("Logout");
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 90, 37));

        btnManageWaitlist1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManageWaitlist1.setForeground(new java.awt.Color(255, 255, 255));
        btnManageWaitlist1.setText("Manage Waitlist");
        btnManageWaitlist1.setBorderPainted(false);
        btnManageWaitlist1.setContentAreaFilled(false);
        btnManageWaitlist1.setFocusPainted(false);
        btnManageWaitlist1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManageWaitlist1.addActionListener(this::btnManageWaitlist1ActionPerformed);
        sidebarPanel.add(btnManageWaitlist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 248, 210, 37));

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.WEST);

        jTabbedPane1.addTab("Dashboard", jPanel1);
        jTabbedPane1.addTab("Register Walk-in", jPanel2);
        jTabbedPane1.addTab("Generate Token", jPanel3);
        jTabbedPane1.addTab("Assign Doctor", jPanel4);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageWaitlist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageWaitlist1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageWaitlist1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WithTabbedPane().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignDoctor;
    private javax.swing.JButton btnGenerateToken;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageWaitlist1;
    private javax.swing.JButton btnRegisterWalkin;
    private view.DashboardView jPanel1;
    private view.RegisterWalkinView jPanel2;
    private view.GenerateTokenView jPanel3;
    private view.AssignToDoctorView jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHospicare;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
